name: msvc-dev-cmd

on:
  pull_request:
  push:
    branches:
      - master
      - release/*
      - test-old-branch
  schedule:
    - cron: '0 6 * * *'

jobs:
  test:
    name: default
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Download Internet
        run: npm install
      - name: Enable Developer Command Prompt
        uses: ./
      - name: Compile and run some C code
        shell: cmd
        run: |
          cl.exe hello.c
          hello.exe
  audit:
    name: npm audit
    runs-on: windows-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v1
      - run: npm install
      - run: npm audit --audit-level=moderate
